import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    appTitle: "Kisan Mitra",
    smartAgriHub: "Smart Agri Hub",
    tagline: "Smart Farming Starts With Better Information",
    heroHeading1: "Smart Farming Starts With",
    heroHeading2: "Better Information",
    heroSubtitle: "Get weather, crop, market and farming information in one place. Empowering farmers with hyper-local forecasts, daily mandi prices, crop disease diagnosis, and multilingual AI advisory.",
    nextGenPlatform: "Next-Gen Agricultural Intelligence Platform",
    exploreTools: "Explore Farming Tools",
    askAI: "Ask Kisan AI",
    freeForFarmers: "Free for Farmers",
    langsSupported: "3 Langs",
    langsList: "EN | HI | MR",
    aiAssistance24x7: "24x7",
    aiAgriDesc: "AI Agri Assistance",
    liveWeather: "Live Weather",
    todaysMandiSnapshot: "Today's Mandi Snapshot",
    viewAll: "View All →",
    perQuintal: "/ Quintal",
    humidity: "Humidity",
    rainChance: "Rain Chance",
    windSpeed: "Wind Speed",
    uvIndex: "UV Index",
    feelsLike: "Feels like",
    comprehensiveSuite: "Comprehensive Suite",
    everythingFarmerNeeds: "Everything A Progressive Farmer Needs",
    featureSubtitle: "From climate-smart weather advisories to instant pathology diagnostics and direct market price intelligence.",
    gotFarmingProblem: "Got A Farming Problem? Ask Kisan AI Assistant!",
    aiBannerDesc: "Ask in English, हिन्दी, or मराठी. Get immediate solutions for leaf yellowing, pest treatments, crop sowing dates, fertilizer dosage calculations, and government scheme eligibility.",
    startChatAI: "Start Chat with Kisan AI",
    uploadPlantPhoto: "Upload Plant Photo",
    sampleQuestions: "Sample Questions You Can Ask",
    latestBulletins: "Latest Agricultural Bulletins",
    bulletinSubtitle: "Verified announcements from Ministry of Agriculture, IMD, and ICAR.",
    viewAllBulletins: "View All Bulletins →",

    // Navigation
    navHome: "Home",
    navDashboard: "Dashboard",
    navWeather: "Weather",
    navCrops: "Crops",
    navDiseases: "Pest & Disease",
    navMarket: "Mandi Prices",
    navNews: "Agri News",
    navSchemes: "Govt Schemes",
    navAIAssistant: "Kisan AI",
    navAdmin: "Admin Panel",
    navLogin: "Login",
    navRegister: "Register",
    navProfile: "My Profile",
    navLogout: "Logout",
    welcome: "Welcome",
    quickAccess: "Quick Access",

    // Weather Page
    agrometForecast: "Agricultural Agromet Forecast",
    weatherAdvisories: "Weather & Spray Advisories",
    useMyGps: "Use My GPS",
    detectingGps: "Detecting...",
    fieldAdvisory: "Field Operation Advisory",
    hourlyTrend: "Hourly Trend (Next 16 Hours)",
    extendedForecast7Day: "7-Day Extended Forecast",
    sunrise: "Sunrise",
    sunset: "Sunset",

    // Crops Page
    cropEncyclopedia: "National Crop Encyclopedia",
    cropGuidesTitle: "Crop Cultivation & Farming Guides",
    cropGuidesSubtitle: "Explore scientific agronomy practices, soil requirements, fertilizer dosing (NPK), and sowing timelines across 5 major categories.",
    searchCrops: "Search crops (e.g. Wheat, Tomato)...",
    category: "Category",
    season: "Season",
    sowing: "Sowing",
    soil: "Soil",
    water: "Water",
    viewFullGuide: "View Full Farming Guide",
    noCropsFound: "No crops found matching your criteria",
    resetFilters: "Reset Filters",

    // Diseases Page
    pestDiagnosisTitle: "Pest & Disease Diagnosis",
    pestDiagnosisSubtitle: "Identify leaf symptoms, fungal blights, viral curl diseases, and insect infestations with certified chemical and biological treatment protocols.",
    searchSymptoms: "Search symptoms or pests...",
    aiImageDiagnosis: "AI Crop Image Diagnosis",
    instantAI: "Instant AI",
    uploadCropImage: "Click to upload crop image",
    supportsFormats: "Supports JPG, PNG, WebP",
    symptoms: "Symptoms (लक्षण)",
    causes: "Possible Causes (कारण)",
    treatment: "Recommended Treatment (रोकथाम व उपचार)",
    prevention: "Preventative Agronomy (बचाव)",
    filterCrop: "Filter Crop",
    diseaseType: "Disease Type",

    // Market Prices Page
    dailyMandiRates: "Daily Mandi / Market Rates",
    mandiSubtitle: "Real-time modal, minimum, and maximum prices per quintal across agricultural produce market committees (APMC).",
    priceTrend15Day: "15-Day Modal Price Trend for",
    historicalPriceIndex: "Historical commodity price index (₹ per Quintal)",
    selectCrop: "Select Crop",
    state: "State",
    district: "District",
    sortBy: "Sort By",
    latestDate: "Latest Date",
    highestPriceFirst: "Highest Price First",
    lowestPriceFirst: "Lowest Price First",
    commodityCrop: "Commodity / Crop",
    mandiMarket: "Mandi / Market",
    stateDistrict: "State & District",
    minRate: "Min Rate",
    maxRate: "Max Rate",
    modalPrice: "Modal Price",
    date: "Date",

    // Schemes Page
    govtSchemesTitle: "Government Agriculture Schemes",
    govtSchemesSubtitle: "Verified Indian Central & State Government farmer welfare initiatives, subsidies, crop insurance, and Kisan Credit Card facilities.",
    searchSchemes: "Search schemes (e.g. PM-KISAN)...",
    benefitsSupport: "Financial Benefits & Support",
    eligibilityCriteria: "Eligibility Criteria",
    requiredDocuments: "Required Documents",
    howToApply: "How to Apply",
    visitOfficialPortal: "Visit Official Portal",

    // AI Assistant Page
    kisanAIAssistant: "Kisan AI Assistant",
    online: "Online",
    multilingualAdvisor: "Multilingual agricultural advisor (English, हिन्दी, मराठी)",
    typeQuestionPlaceholder: "Ask a question about crops, fertilizers, pests, or schemes...",
    analyzingQuery: "Kisan AI is analyzing your query...",
    send: "Send",
    resetChat: "Reset Chat",

    // Footer
    farmingTools: "Farming Tools",
    resources: "Resources",
    farmerHelplines: "Farmer Helplines",
    tollFreeNumber: "1800-180-1551",
    tollFreeLabel: "Toll-Free Kisan Call Center",
    supportDesk: "Kisan Mitra Support Desk",
    copyright: "Kisan Mitra Smart Farmer Platform. Built for Indian Farmers.",

    // General
    search: "Search",
    filter: "Filter",
    all: "All",
    viewDetails: "View Details",
    loading: "Loading information...",
    retry: "Try Again",
    noData: "No data available at the moment."
  },
  hi: {
    appTitle: "किसान मित्र",
    smartAgriHub: "स्मार्ट कृषि केंद्र",
    tagline: "स्मार्ट खेती, बेहतर जानकारी के साथ",
    heroHeading1: "स्मार्ट खेती की शुरुआत",
    heroHeading2: "सटीक जानकारी से",
    heroSubtitle: "मौसम पूर्वानुमान, फसलों की संपूर्ण जानकारी, दैनिक मंडी भाव, कीट-रोग पहचान और सरकारी योजनाएं एक ही स्थान पर प्राप्त करें।",
    nextGenPlatform: "आधुनिक कृषि सूचना एवं परामर्श मंच",
    exploreTools: "कृषि सेवाएं देखें",
    askAI: "किसान एआई से पूछें",
    freeForFarmers: "किसानों के लिए निःशुल्क",
    langsSupported: "3 भाषाएं",
    langsList: "EN | हिन्दी | मराठी",
    aiAssistance24x7: "24x7",
    aiAgriDesc: "एआई कृषि सहायता",
    liveWeather: "ताज़ा मौसम",
    todaysMandiSnapshot: "आज का मंडी भाव",
    viewAll: "सभी देखें →",
    perQuintal: "/ क्विंटल",
    humidity: "नमी (आर्द्रता)",
    rainChance: "बारिश की संभावना",
    windSpeed: "हवा की गति",
    uvIndex: "यूवी इंडेक्स",
    feelsLike: "अनुभूत तापमान",
    comprehensiveSuite: "संपूर्ण कृषि समाधान",
    everythingFarmerNeeds: "प्रगतिशील किसान की हर आवश्यकता",
    featureSubtitle: "मौसम सलाह से लेकर रोग निदान और दैनिक मंडी भाव तक, सब कुछ एक जगह।",
    gotFarmingProblem: "खेती में कोई समस्या? किसान एआई से पूछें!",
    aiBannerDesc: "हिंदी, मराठी या अंग्रेजी में पूछें। पत्तियों के पीलेपन, कीटनाशक, बुवाई समय, खाद की मात्रा और सरकारी योजनाओं की सटीक जानकारी पाएं।",
    startChatAI: "किसान एआई से बात करें",
    uploadPlantPhoto: "पौधे का फोटो अपलोड करें",
    sampleQuestions: "आप इस प्रकार के प्रश्न पूछ सकते हैं",
    latestBulletins: "ताज़ा कृषि समाचार एवं बुलेटिन",
    bulletinSubtitle: "कृषि मंत्रालय, मौसम विभाग (IMD) और ICAR द्वारा सत्यापित सूचनाएं।",
    viewAllBulletins: "सभी समाचार देखें →",

    // Navigation
    navHome: "होम",
    navDashboard: "डैशबोर्ड",
    navWeather: "मौसम",
    navCrops: "फसलें",
    navDiseases: "रोग व कीट",
    navMarket: "मंडी भाव",
    navNews: "कृषि समाचार",
    navSchemes: "सरकारी योजनाएं",
    navAIAssistant: "किसान एआई",
    navAdmin: "एडमिन पैनल",
    navLogin: "लॉगिन",
    navRegister: "पंजीकरण",
    navProfile: "मेरी प्रोफाइल",
    navLogout: "लॉगआउट",
    welcome: "स्वागत है",
    quickAccess: "त्वरित सेवाएं",

    // Weather Page
    agrometForecast: "कृषि मौसम पूर्वानुमान (Agromet)",
    weatherAdvisories: "मौसम एवं कीटनाशक छिड़काव सलाह",
    useMyGps: "मेरा जीपीएस (GPS) उपयोग करें",
    detectingGps: "स्थान खोजा जा रहा है...",
    fieldAdvisory: "खेत कार्य हेतु मौसम सलाह",
    hourlyTrend: "प्रति घंटे का पूर्वानुमान (अगले 16 घंटे)",
    extendedForecast7Day: "7 दिनों का विस्तृत मौसम पूर्वानुमान",
    sunrise: "सूर्योदय",
    sunset: "सूर्यास्त",

    // Crops Page
    cropEncyclopedia: "राष्ट्रीय फसल ज्ञानकोश",
    cropGuidesTitle: "फसल उत्पादन एवं कृषि मार्गदर्शिका",
    cropGuidesSubtitle: "वैज्ञानिक कृषि पद्धतियां, मिट्टी की आवश्यकताएं, उर्वरक मात्रा (NPK) और बुवाई समय की संपूर्ण जानकारी।",
    searchCrops: "फसल खोजें (जैसे गेहूं, टमाटर)...",
    category: "श्रेणी",
    season: "मौसम / ऋतु",
    sowing: "बुवाई",
    soil: "मिट्टी",
    water: "पानी",
    viewFullGuide: "पूरी फसल गाइड देखें",
    noCropsFound: "आपके द्वारा खोजी गई कोई फसल नहीं मिली",
    resetFilters: "फ़िल्टर रीसेट करें",

    // Diseases Page
    pestDiagnosisTitle: "कीट एवं फसल रोग पहचान",
    pestDiagnosisSubtitle: "पत्तियों के लक्षण, फफूंद जनित रोग, लीफ कर्ल और कीट प्रकोप की पहचान और प्रमाणित रासायनिक व जैविक उपचार।",
    searchSymptoms: "लक्षण या कीट का नाम खोजें...",
    aiImageDiagnosis: "एआई फसल रोग फोटो जांच",
    instantAI: "त्वरित एआई",
    uploadCropImage: "फसल की फोटो अपलोड करने के लिए क्लिक करें",
    supportsFormats: "JPG, PNG, WebP समर्थित",
    symptoms: "रोग के लक्षण (Symptoms)",
    causes: "संभावित कारण (Causes)",
    treatment: "अनुशंसित उपचार (Treatment)",
    prevention: "बचाव के उपाय (Prevention)",
    filterCrop: "फसल चुनें",
    diseaseType: "रोग का प्रकार",

    // Market Prices Page
    dailyMandiRates: "दैनिक मंडी / बाजार भाव",
    mandiSubtitle: "कृषि उपज मंडी समितियों (APMC) के न्यूनतम, अधिकतम और मॉडल भाव (प्रति क्विंटल)।",
    priceTrend15Day: "15 दिनों का मूल्य रुझान -",
    historicalPriceIndex: "ऐतिहासिक मूल्य ग्राफ (₹ प्रति क्विंटल)",
    selectCrop: "फसल चुनें",
    state: "राज्य",
    district: "जिला",
    sortBy: "क्रमबद्ध करें",
    latestDate: "नवीनतम दिनांक",
    highestPriceFirst: "अधिकतम भाव पहले",
    lowestPriceFirst: "न्यूनतम भाव पहले",
    commodityCrop: "फसल / जींस",
    mandiMarket: "मंडी / बाजार",
    stateDistrict: "राज्य व जिला",
    minRate: "न्यूनतम भाव",
    maxRate: "अधिकतम भाव",
    modalPrice: "मॉडल भाव",
    date: "दिनांक",

    // Schemes Page
    govtSchemesTitle: "सरकारी कृषि योजनाएं व अनुदान",
    govtSchemesSubtitle: "भारत सरकार एवं राज्य सरकारों की किसान कल्याणकारी योजनाएं, सब्सिडी, फसल बीमा और किसान क्रेडिट कार्ड।",
    searchSchemes: "योजना खोजें (जैसे पीएम-किसान)...",
    benefitsSupport: "वित्तीय लाभ एवं सहायता",
    eligibilityCriteria: "पात्रता मापदंड",
    requiredDocuments: "आवश्यक दस्तावेज",
    howToApply: "आवेदन कैसे करें",
    visitOfficialPortal: "आधिकारिक पोर्टल पर जाएं",

    // AI Assistant Page
    kisanAIAssistant: "किसान एआई सहायक",
    online: "ऑनलाइन",
    multilingualAdvisor: "बहुभाषी कृषि सलाहकार (English, हिन्दी, मराठी)",
    typeQuestionPlaceholder: "फसल, खाद, कीट या योजनाओं से जुड़ा सवाल पूछें...",
    analyzingQuery: "किसान एआई आपके प्रश्न का विश्लेषण कर रहा है...",
    send: "भेजें",
    resetChat: "नया चैट शुरू करें",

    // Footer
    farmingTools: "कृषि सेवाएं",
    resources: "संसाधन व लिंक",
    farmerHelplines: "किसान हेल्पलाइन",
    tollFreeNumber: "1800-180-1551",
    tollFreeLabel: "टोल-फ्री किसान कॉल सेंटर",
    supportDesk: "किसान मित्र सहायता डेस्क",
    copyright: "किसान मित्र स्मार्ट फार्मर प्लेटफॉर्म। भारतीय किसानों के लिए समर्पित।",

    // General
    search: "खोजें",
    filter: "फ़िल्टर",
    all: "सभी",
    viewDetails: "विवरण देखें",
    loading: "जानकारी लोड हो रही है...",
    retry: "पुनः प्रयास करें",
    noData: "फिलहाल कोई डेटा उपलब्ध नहीं है।"
  },
  mr: {
    appTitle: "किसान मित्र",
    smartAgriHub: "स्मार्ट कृषी हब",
    tagline: "स्मार्ट शेती, अचूक माहितीच्या बळावर",
    heroHeading1: "स्मार्ट शेतीची सुरुवात",
    heroHeading2: "अचूक माहितीने",
    heroSubtitle: "हवामान अंदाज, पिकांची सविस्तर माहिती, दैनंदिन बाजार भाव, रोग-कीड निदान आणि शासकीय योजना आता एकाच ठिकाणी मिळवा.",
    nextGenPlatform: "अत्याधुनिक कृषी माहिती व सल्लागार व्यासपीठ",
    exploreTools: "शेती सेवा पहा",
    askAI: "किसान AI ला विचारा",
    freeForFarmers: "शेतकऱ्यांसाठी मोफत",
    langsSupported: "३ भाषा",
    langsList: "EN | हिन्दी | मराठी",
    aiAssistance24x7: "२४x७",
    aiAgriDesc: "AI कृषी सहाय्य",
    liveWeather: "थेट हवामान",
    todaysMandiSnapshot: "आजचे बाजार भाव",
    viewAll: "सर्व पहा →",
    perQuintal: "/ क्विंटल",
    humidity: "हवेतील ओलावा (आर्द्रता)",
    rainChance: "पावसाची शक्यता",
    windSpeed: "वाऱ्याचा वेग",
    uvIndex: "अल्ट्राव्हायोलेट इंडेक्स",
    feelsLike: "जावणारा तापमान",
    comprehensiveSuite: "संपूर्ण कृषी उपाय",
    everythingFarmerNeeds: "प्रगतिशील शेतकऱ्यांच्या सर्व गरजा",
    featureSubtitle: "हवामान सल्ल्यापासून ते रोग निदान आणि थेट बाजार भाव विश्लेषणापर्यंत सर्व काही एकाच ठिकाणी.",
    gotFarmingProblem: "शेतीत काही अडचण? किसान AI ला विचारा!",
    aiBannerDesc: "मराठी, हिंदी किंवा इंग्रजीत विचारा. पाने पिवळी पडणे, कीड नियंत्रण, पेरणीची वेळ, खतांचे डोस आणि शासकीय योजनांची अचूक माहिती मिळवा.",
    startChatAI: "किसान AI सोबत बोला",
    uploadPlantPhoto: "झाडाचा फोटो अपलोड करा",
    sampleQuestions: "तुम्ही असे प्रश्न विचारू शकता",
    latestBulletins: "ताज्या कृषी घडामोडी व बातम्या",
    bulletinSubtitle: "कृषी मंत्रालय, हवामान विभाग (IMD) आणि ICAR कडून प्रमाणित माहिती.",
    viewAllBulletins: "सर्व बातम्या पहा →",

    // Navigation
    navHome: "मुख्यपृष्ठ",
    navDashboard: "डॅशबोर्ड",
    navWeather: "हवामान",
    navCrops: "पिके",
    navDiseases: "रोग व कीड",
    navMarket: "बाजार भाव",
    navNews: "कृषी बातम्या",
    navSchemes: "शासकीय योजना",
    navAIAssistant: "किसान AI",
    navAdmin: "प्रशासन",
    navLogin: "लॉगिन",
    navRegister: "नोंदणी",
    navProfile: "माझे प्रोफाईल",
    navLogout: "लॉगआउट",
    welcome: "स्वागत आहे",
    quickAccess: "द्रुत सेवा",

    // Weather Page
    agrometForecast: "कृषी हवामान अंदाज (Agromet)",
    weatherAdvisories: "हवामान व औषध फवारणी सल्ला",
    useMyGps: "माझे GPS स्थान वापरा",
    detectingGps: "स्थान शोधत आहे...",
    fieldAdvisory: "शेती कामांसाठी हवामान सल्ला",
    hourlyTrend: "तासनिहाय हवामान कल (पुढील १६ तास)",
    extendedForecast7Day: "७ दिवसांचा सविस्तर हवामान अंदाज",
    sunrise: "सूर्योदय",
    sunset: "सूर्यास्त",

    // Crops Page
    cropEncyclopedia: "राष्ट्रीय पीक ज्ञानकोश",
    cropGuidesTitle: "पीक लागवड व शेती मार्गदर्शिका",
    cropGuidesSubtitle: "शास्त्रीय कृषी पद्धती, जमिनीची गरज, खतांचे प्रमाण (NPK) आणि पेरणीच्या वेळेची संपूर्ण माहिती.",
    searchCrops: "पीक शोधा (उदा. गहू, टोमॅटो)...",
    category: "प्रवर्ग / जात",
    season: "हंगाम",
    sowing: "पेरणी / लागवड",
    soil: "जमीन / माती",
    water: "पाणी",
    viewFullGuide: "संपूर्ण पीक मार्गदर्शिका पहा",
    noCropsFound: "तुम्ही शोधलेले पीक सापडले नाही",
    resetFilters: "फिल्टर रीसेट करा",

    // Diseases Page
    pestDiagnosisTitle: "कीड व पीक रोग निदान",
    pestDiagnosisSubtitle: "पानावरील लक्षणे, बुरशीजन्य करपा, चुरडा-मुरडा आणि किडींचा प्रादुर्भाव ओळखा आणि प्रमाणित रासायनिक व जैविक उपाय मिळवा.",
    searchSymptoms: "लक्षणे किंवा कीड शोधा...",
    aiImageDiagnosis: "AI पीक रोग फोटो तपासणी",
    instantAI: "त्वरित AI",
    uploadCropImage: "पिकाचा फोटो अपलोड करण्यासाठी क्लिक करा",
    supportsFormats: "JPG, PNG, WebP समर्थित",
    symptoms: "रोगाची लक्षणे (Symptoms)",
    causes: "संभाव्य कारणे (Causes)",
    treatment: "शिफारस केलेले उपचार (Treatment)",
    prevention: "प्रतिबंधात्मक उपाय (Prevention)",
    filterCrop: "पीक निवडा",
    diseaseType: "रोगाचा प्रकार",

    // Market Prices Page
    dailyMandiRates: "दैनंदिन बाजार / कृषी उत्पन्न बाजार समिती भाव",
    mandiSubtitle: "बाजार समित्यांमधील (APMC) किमान, कमाल आणि सरासरी (मॉडेल) दर (प्रति क्विंटल).",
    priceTrend15Day: "१५ दिवसांचा दर कल -",
    historicalPriceIndex: "ऐतिहासिक भाव आलेख (₹ प्रति क्विंटल)",
    selectCrop: "पीक निवडा",
    state: "राज्य",
    district: "जिल्हा",
    sortBy: "क्रमाने लावा",
    latestDate: "नवीनतम तारीख",
    highestPriceFirst: "कमाल भाव आधी",
    lowestPriceFirst: "किमान भाव आधी",
    commodityCrop: "पीक / शेतीमाल",
    mandiMarket: "बाजार समिती / मार्केट",
    stateDistrict: "राज्य व जिल्हा",
    minRate: "किमान दर",
    maxRate: "कमाल दर",
    modalPrice: "सरासरी दर",
    date: "तारीख",

    // Schemes Page
    govtSchemesTitle: "शासकीय कृषी योजना व अनुदान",
    govtSchemesSubtitle: "केंद्र व राज्य शासनाच्या शेतकरी कल्याणकारी योजना, सबसिडी, पीक विमा आणि किसान क्रेडिट कार्ड.",
    searchSchemes: "योजना शोधा (उदा. पीएम-किसान)...",
    benefitsSupport: "आर्थिक लाभ आणि सहाय्य",
    eligibilityCriteria: "पात्रता निकष",
    requiredDocuments: "आवश्यक कागदपत्रे",
    howToApply: "अर्ज कसा करावा",
    visitOfficialPortal: "अधिकृत पोर्टलला भेट द्या",

    // AI Assistant Page
    kisanAIAssistant: "किसान AI सहाय्यक",
    online: "ऑनलाइन",
    multilingualAdvisor: "बहुभाषिक कृषी सल्लागार (English, हिन्दी, मराठी)",
    typeQuestionPlaceholder: "पीक, खते, रोग किंवा योजनांबद्दल प्रश्न विचारा...",
    analyzingQuery: "किसान AI आपल्या प्रश्नाचे विश्लेषण करत आहे...",
    send: "पाठवा",
    resetChat: "नवीन चॅट सुरू करा",

    // Footer
    farmingTools: "शेती सेवा",
    resources: "संसाधने व लिंक्स",
    farmerHelplines: "शेतकरी हेल्पलाइन",
    tollFreeNumber: "1800-180-1551",
    tollFreeLabel: "टोल-फ्री किसान कॉल सेंटर",
    supportDesk: "किसान मित्र सहाय्यता कक्ष",
    copyright: "किसान मित्र स्मार्ट फार्मर प्लॅटफॉर्म. भारतीय बळीराजासाठी समर्पित.",

    // General
    search: "शोधा",
    filter: "फिल्टर",
    all: "सर्व",
    viewDetails: "तपशील पहा",
    loading: "माहिती लोड होत आहे...",
    retry: "पुन्हा प्रयत्न करा",
    noData: "सध्या कोणतीही माहिती उपलब्ध नाही."
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('kisan_lang') || 'en';
  });

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('kisan_lang', lang);
  };

  const t = translations[language] || translations.en;

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
